#
# Ci-dessous la config qui permet de lancer convergence-docker
#
# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#

version: "3.5"

services:

  ############################
  # sudoc-api
  # API de sudoc
  # (écrite en java spring boot)
  sudoc-api:
    image: abesesr/sudoc:${SUDOC_API_VERSION}
    container_name: sudoc-api
    restart: no
    mem_limit: ${MEM_LIMIT}
    environment:
      # Pour basculer sur bon application-xxx.properties préalablement embarqué
      # dans le code ici:
      # https://github.com/abes-esr/abes-hello-back/tree/develop/web/src/main/resources/
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      # Pour surcharger les paramètres spring du application-xxx.properties
      # ci-dessous via le système de .env de docker
      # https://www.linkedin.com/pulse/externalizing-properties-spring-boot-application-docker-phani-bushan
      # pour la liste de tous les champs qu'on peut surcharger,
      # voir le contenu des application-xxx.properties embarqués dans le code sources
      SPRING_DATASOURCE_URL: ${SUDOC_API_SPRING_DATASOURCE_BASEXML_JDBCURL}
      SPRING_DATASOURCE_USERNAME: ${SUDOC_API_SPRING_DATASOURCE_BASEXML_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SUDOC_API_SPRING_DATASOURCE_BASEXML_PASSWORD}
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: ${API_SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      LOGGING_LEVEL_FR_ABES_SUDOC: ${CONVERGENCE_API_LOGGING_LEVEL}
      _JAVA_OPTIONS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=0.0.0.0"
    ports:
      - ${SUDOC_API_HTTP_PORT}:8082
      - 15088:9090
      - 1099:1099
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=convergence-sudoc-api"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"
      # pour que les mises à jour de cette image soient auto-déployées par watchtower
      - "com.centurylinklabs.watchtower.scope=convergence-watchtower-scope"

  #########################################
  # best-ppn-api
  # API en spring
  best-ppn-api:
    image: abesesr/convergence:${BESTPPNAPI_VERSION}
    container_name: best-ppn-api
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ${LOGSKBART_API_PATH_TSVFILE}:/app/tempLog/
    ports:
      - ${BEST_PPN_API_HTTP_PORT}:8083
    environment:
      # Pour basculer sur bon application-xxx.properties préalablement embarqué
      # dans le code ici:
      # https://github.com/abes-esr/abes-hello-back/tree/develop/web/src/main/resources/
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      # Pour surcharger les paramètres spring du application-xxx.properties
      # ci-dessous via le système de .env de docker
      # https://www.linkedin.com/pulse/externalizing-properties-spring-boot-application-docker-phani-bushan
      # pour la liste de tous les champs qu'on peut surcharger,
      # voir le contenu des application-xxx.properties embarqués dans le code sources
      ABES_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      ABES_KAFKA_REGISTRY_URL: ${KAFKA_REGISTRY_URL}
      ABES_KAFKA_CONCURRENCY_NBTHREAD: ${KAFKA_CONCURRENCY_NBTHREAD}
      SPRING_DATASOURCE_BASEXML_JDBCURL: ${BEST_PPN_API_SUDOC_API_SPRING_DATASOURCE_BASEXML_JDBCURL}
      SPRING_DATASOURCE_BASEXML_USERNAME: ${BEST_PPN_API_SUDOC_API_SPRING_DATASOURCE_BASEXML_USERNAME}
      SPRING_DATASOURCE_BASEXML_PASSWORD: ${BEST_PPN_API_SUDOC_API_SPRING_DATASOURCE_BASEXML_PASSWORD}
      SPRING_DATASOURCE_BACON_JDBCURL: ${BACON_JDBCURL}
      SPRING_DATASOURCE_BACON_USERNAME: ${BACON_USERNAME}
      SPRING_DATASOURCE_BACON_PASSWORD: ${BACON_PASSWORD}
      URL_ONLINEID2PPN: http://sudoc-api:8082/api/v1/online_identifier_2_ppn
      URL_PRINTID2PPN: http://sudoc-api:8082/api/v1/print_identifier_2_ppn
      URL_DAT2PPN: http://sudoc-api:8082/api/v1/dat2ppn
      URL_DOI2PPN: http://sudoc-api:8082/api/v1/doi_identifier_2_ppn
      MAIL_WS_URL: ${MAIL_WS_URL}
      MAIL_WS_RECIPIENT: ${MAIL_WS_RECIPIENT_KBART_2_BACON}
      SERVEUR_URL: ${SERVEUR_URL}
      SPRING_JPA_BACON_SHOW-SQL: false
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=convergence-best-ppn-api"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"
      # pour que les mises à jour de cette image soient auto-déployées par watchtower
      - "com.centurylinklabs.watchtower.scope=convergence-watchtower-scope"

  #######################################
  # convergence-watchtower
  # Conteneur chargé de mettre à jour automatiquement toutes les N secondes
  # les images docker des conteneurs surveillés (via le système de label/scope de watchtower)
  # plus d'info : https://containrrr.dev/watchtower
  # cf README.md pour explications : https://github.com/abes-esr/convergence-docker#d%C3%A9ploiement-continu
  convergence-watchtower:
    image: containrrr/watchtower:1.4.0
    container_name: convergence-watchtower
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_DEBUG: "false"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
      WATCHTOWER_RUN_ONCE: ${CONVERGENCE_WATCHTOWER_RUN_ONCE}
      WATCHTOWER_NOTIFICATIONS: "slack"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${CONVERGENCE_WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: ${CONVERGENCE_WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER}
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#notif-convergence-watchtower"
      WATCHTOWER_SCOPE: "convergence-watchtower-scope"
    labels:
      - "com.centurylinklabs.watchtower.scope=convergence-watchtower-scope"

